<template>
  <div class="app-container">
    <el-form-renderer :content="content"/>
  </div>
</template>

<script>
import ElFormRenderer from '@/components/ElFormRender/render'

export default {
  components: {
    ElFormRenderer
  },
  data() {
    return {
      content: [
  {
    'id': 'f75c56c0-70c0-e811-80c3-00155d0a2546',
    'groupId': null,
    'name': '基本资料',
    'busiObjName': null,
    'hasSystemNorm': false,
    'children': [
      {
        'id': '5e03ccdf-70c0-e811-80c3-00155d0a2546', // ID
        'name': '数值', // 控件名称 label
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546', // 所属分组
        'isSystem': false, // 是否系统级  前台不需要
        'isReadonly': false, // 是否只读
        'defaultValue': '0', // 默认值
        'propertyType': 0, // 前端不用
        'serviceLine': '运营', // 根据传进来的参数，判断是否只读，比如传进来的是运营，则可以填写，其他的不能填写
        'modifyReasonReq': false, // 修改的时候显示文本框 需要填写修改属性，页面编辑状态才需要
        'isMustFill': false, // 是否必填
        'valueType': '数值', // 控件类型
        'remark': '数值', // 前台不需要
        'unit': '', // 数字类型时  显示的单位
        'dec': 2, // 数字类型时，保留位
        'limitFileCount': 0, // 文件类型时  上传文件限制数量
        'dataItems': '', // 枚举类型时对应的值，逗号分隔
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '', // 类型为业务参数时，选择的业务参数名字
        'fieldName': null,
        'formulaCondition': null, // 当字段有公式计算时 公式表达式
        'formulaConditionText': null, // 当字段有公式计算时 公式表达式文本形式
        'filterRuleText': null, // 公式的计算规则的文本形式
        'isRefByBusinessData': 0,
        'orderBy': 2, // 页面字段显示顺序
        'parentName': null,
        'isOneLine': false, // 是否独占一行
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false, // 是否是隐藏的属性
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false, // 重复分组时用到，是否是主键，主键唯一校验
        'fieldType': null,
        'groupType': 0, // 0 不可重复分组  1可重复分组
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': false // 是否允许多选
      },
      {
        'id': '62c4b5f2-70c0-e811-80c3-00155d0a2546',
        'name': '枚举',
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546',
        'isSystem': false,
        'isReadonly': false,
        'defaultValue': '',
        'propertyType': 0,
        'serviceLine': '',
        'modifyReasonReq': false,
        'isMustFill': false,
        'valueType': '枚举',
        'remark': '枚举 允许多选',
        'unit': '',
        'dec': 2,
        'limitFileCount': 0,
        'dataItems': '一，二，三',
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '',
        'fieldName': null,
        'formulaCondition': null,
        'formulaConditionText': null,
        'filterRuleText': null,
        'isRefByBusinessData': 0,
        'orderBy': 3,
        'parentName': null,
        'isOneLine': false,
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false,
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false,
        'fieldType': null,
        'groupType': 0,
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': true
      },
      {
        'id': '79917d01-71c0-e811-80c3-00155d0a2546',
        'name': '日期',
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546',
        'isSystem': false,
        'isReadonly': false,
        'defaultValue': '',
        'propertyType': 0,
        'serviceLine': '运营',
        'modifyReasonReq': false,
        'isMustFill': false,
        'valueType': '日期',
        'remark': '日期  独占一行',
        'unit': '',
        'dec': 2,
        'limitFileCount': 0,
        'dataItems': '',
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '',
        'fieldName': null,
        'formulaCondition': null,
        'formulaConditionText': null,
        'filterRuleText': null,
        'isRefByBusinessData': 0,
        'orderBy': 4,
        'parentName': null,
        'isOneLine': true,
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false,
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false,
        'fieldType': null,
        'groupType': 0,
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': false
      },
      {
        'id': '0a5afc0e-71c0-e811-80c3-00155d0a2546',
        'name': '备注',
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546',
        'isSystem': false,
        'isReadonly': false,
        'defaultValue': '备注',
        'propertyType': 0,
        'serviceLine': '运营',
        'modifyReasonReq': false,
        'isMustFill': false,
        'valueType': '备注',
        'remark': '备注 文本域',
        'unit': '',
        'dec': 2,
        'limitFileCount': 0,
        'dataItems': '',
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '',
        'fieldName': null,
        'formulaCondition': null,
        'formulaConditionText': null,
        'filterRuleText': null,
        'isRefByBusinessData': 0,
        'orderBy': 5,
        'parentName': null,
        'isOneLine': false,
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false,
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false,
        'fieldType': null,
        'groupType': 0,
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': false
      },
      {
        'id': '4d8b551c-71c0-e811-80c3-00155d0a2546',
        'name': '附件',
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546',
        'isSystem': false,
        'isReadonly': false,
        'defaultValue': '',
        'propertyType': 0,
        'serviceLine': '',
        'modifyReasonReq': false,
        'isMustFill': false,
        'valueType': '附件',
        'remark': '附件上传',
        'unit': '',
        'dec': 2,
        'limitFileCount': 10,
        'dataItems': '',
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '',
        'fieldName': null,
        'formulaCondition': null,
        'formulaConditionText': null,
        'filterRuleText': null,
        'isRefByBusinessData': 0,
        'orderBy': 6,
        'parentName': null,
        'isOneLine': false,
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false,
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false,
        'fieldType': null,
        'groupType': 0,
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': false
      },
      {
        'id': 'a556562e-71c0-e811-80c3-00155d0a2546',
        'name': '业务参数',
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546',
        'isSystem': false,
        'isReadonly': false,
        'defaultValue': '',
        'propertyType': 0,
        'serviceLine': '运营',
        'modifyReasonReq': false,
        'isMustFill': false,
        'valueType': '业务参数',
        'remark': '从业务参数中取值',
        'unit': '',
        'dec': 2,
        'limitFileCount': 0,
        'dataItems': '',
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '计量单位',
        'fieldName': null,
        'formulaCondition': null,
        'formulaConditionText': null,
        'filterRuleText': null,
        'isRefByBusinessData': 0,
        'orderBy': 7,
        'parentName': null,
        'isOneLine': false,
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false,
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false,
        'fieldType': null,
        'groupType': 0,
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': false
      },
      {
        'id': '043da7d0-70c0-e811-80c3-00155d0a2546',
        'name': '文本',
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546',
        'isSystem': false,
        'isReadonly': true,
        'defaultValue': '默认文本 只读',
        'propertyType': 0,
        'serviceLine': '运营',
        'modifyReasonReq': false,
        'isMustFill': false,
        'valueType': '文本',
        'remark': '说明',
        'unit': '',
        'dec': 2,
        'limitFileCount': 0,
        'dataItems': '',
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '',
        'fieldName': null,
        'formulaCondition': null,
        'formulaConditionText': null,
        'filterRuleText': null,
        'isRefByBusinessData': 0,
        'orderBy': 1,
        'parentName': null,
        'isOneLine': false,
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false,
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false,
        'fieldType': null,
        'groupType': 0,
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': false
      },
      {
        'id': 'dc418f6d-72c0-e811-80c3-00155d0a2546',
        'name': '汇总计算',
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546',
        'isSystem': false,
        'isReadonly': false,
        'defaultValue': '',
        'propertyType': 0,
        'serviceLine': '运营',
        'modifyReasonReq': false,
        'isMustFill': false,
        'valueType': '数值',
        'remark': '通过列表数据汇总计算',
        'unit': '',
        'dec': 2,
        'limitFileCount': 0,
        'dataItems': '',
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '',
        'fieldName': null,
        'formulaCondition': '{"formulaSummary":"项目.列表表内编辑.分数"}',
        'formulaConditionText': '汇总计算=Sum([项目.列表表内编辑.分数])',
        'filterRuleText': '',
        'isRefByBusinessData': 0,
        'orderBy': 8,
        'parentName': null,
        'isOneLine': false,
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false,
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false,
        'fieldType': null,
        'groupType': 0,
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': false
      }
    ],
    'groupType': 0,
    'dataFromType': 1,
    'refBusinessObjectGUID': null,
    'groupField': '',
    'groupField__text': '',
    'sumField': '',
    'sumField__text': '',
    'refBusinessObjectGroupName': '',
    'refBusinessObjectGroupId': null,
    'selectSumObjectValue': '',
    'selectSumObjectValue__text': '',
    'orderBy': 31,
    'regionId': 'd8f50b89-430d-45c1-af1e-c2658594b07a',
    'displayStyle': '有边框',
    'interfaceId': null,
    'interfaceField': '',
    'initializationData': null,
    'dataModelType': '在表编辑',
    'labelWidth': 0
  },
  {
    'id': 'f75c56c0-70c0-e811-80c3-00155d0a2547',
    'groupId': null,
    'name': '其他信息',
    'busiObjName': null,
    'hasSystemNorm': false,
    'children': [
      {
        'id': '5e03ccdf-70c0-e811-80c3-00155d0a2546', // ID
        'name': '数值', // 控件名称 label
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546', // 所属分组
        'isSystem': false, // 是否系统级  前台不需要
        'isReadonly': false, // 是否只读
        'defaultValue': '0', // 默认值
        'propertyType': 0, // 前端不用
        'serviceLine': '运营', // 根据传进来的参数，判断是否只读，比如传进来的是运营，则可以填写，其他的不能填写
        'modifyReasonReq': false, // 修改的时候显示文本框 需要填写修改属性，页面编辑状态才需要
        'isMustFill': false, // 是否必填
        'valueType': '数值', // 控件类型
        'remark': '数值', // 前台不需要
        'unit': '', // 数字类型时  显示的单位
        'dec': 2, // 数字类型时，保留位
        'limitFileCount': 0, // 文件类型时  上传文件限制数量
        'dataItems': '', // 枚举类型时对应的值，逗号分隔
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '', // 类型为业务参数时，选择的业务参数名字
        'fieldName': null,
        'formulaCondition': null, // 当字段有公式计算时 公式表达式
        'formulaConditionText': null, // 当字段有公式计算时 公式表达式文本形式
        'filterRuleText': null, // 公式的计算规则的文本形式
        'isRefByBusinessData': 0,
        'orderBy': 2, // 页面字段显示顺序
        'parentName': null,
        'isOneLine': false, // 是否独占一行
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false, // 是否是隐藏的属性
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false, // 重复分组时用到，是否是主键，主键唯一校验
        'fieldType': null,
        'groupType': 0, // 0 不可重复分组  1可重复分组
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': false // 是否允许多选
      },
      {
        'id': '62c4b5f2-70c0-e811-80c3-00155d0a2546',
        'name': '枚举',
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546',
        'isSystem': false,
        'isReadonly': false,
        'defaultValue': '',
        'propertyType': 0,
        'serviceLine': '',
        'modifyReasonReq': false,
        'isMustFill': false,
        'valueType': '枚举',
        'remark': '枚举 允许多选',
        'unit': '',
        'dec': 2,
        'limitFileCount': 0,
        'dataItems': '一，二，三',
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '',
        'fieldName': null,
        'formulaCondition': null,
        'formulaConditionText': null,
        'filterRuleText': null,
        'isRefByBusinessData': 0,
        'orderBy': 3,
        'parentName': null,
        'isOneLine': false,
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false,
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false,
        'fieldType': null,
        'groupType': 0,
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': true
      },
      {
        'id': '79917d01-71c0-e811-80c3-00155d0a2546',
        'name': '日期',
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546',
        'isSystem': false,
        'isReadonly': false,
        'defaultValue': '',
        'propertyType': 0,
        'serviceLine': '运营',
        'modifyReasonReq': false,
        'isMustFill': false,
        'valueType': '日期',
        'remark': '日期  独占一行',
        'unit': '',
        'dec': 2,
        'limitFileCount': 0,
        'dataItems': '',
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '',
        'fieldName': null,
        'formulaCondition': null,
        'formulaConditionText': null,
        'filterRuleText': null,
        'isRefByBusinessData': 0,
        'orderBy': 4,
        'parentName': null,
        'isOneLine': true,
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false,
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false,
        'fieldType': null,
        'groupType': 0,
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': false
      },
      {
        'id': '0a5afc0e-71c0-e811-80c3-00155d0a2546',
        'name': '备注',
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546',
        'isSystem': false,
        'isReadonly': false,
        'defaultValue': '备注',
        'propertyType': 0,
        'serviceLine': '运营',
        'modifyReasonReq': false,
        'isMustFill': false,
        'valueType': '备注',
        'remark': '备注 文本域',
        'unit': '',
        'dec': 2,
        'limitFileCount': 0,
        'dataItems': '',
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '',
        'fieldName': null,
        'formulaCondition': null,
        'formulaConditionText': null,
        'filterRuleText': null,
        'isRefByBusinessData': 0,
        'orderBy': 5,
        'parentName': null,
        'isOneLine': false,
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false,
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false,
        'fieldType': null,
        'groupType': 0,
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': false
      },
      {
        'id': '4d8b551c-71c0-e811-80c3-00155d0a2546',
        'name': '附件',
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546',
        'isSystem': false,
        'isReadonly': false,
        'defaultValue': '',
        'propertyType': 0,
        'serviceLine': '',
        'modifyReasonReq': false,
        'isMustFill': false,
        'valueType': '附件',
        'remark': '附件上传',
        'unit': '',
        'dec': 2,
        'limitFileCount': 10,
        'dataItems': '',
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '',
        'fieldName': null,
        'formulaCondition': null,
        'formulaConditionText': null,
        'filterRuleText': null,
        'isRefByBusinessData': 0,
        'orderBy': 6,
        'parentName': null,
        'isOneLine': false,
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false,
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false,
        'fieldType': null,
        'groupType': 0,
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': false
      },
      {
        'id': 'a556562e-71c0-e811-80c3-00155d0a2546',
        'name': '业务参数',
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546',
        'isSystem': false,
        'isReadonly': false,
        'defaultValue': '',
        'propertyType': 0,
        'serviceLine': '运营',
        'modifyReasonReq': false,
        'isMustFill': false,
        'valueType': '业务参数',
        'remark': '从业务参数中取值',
        'unit': '',
        'dec': 2,
        'limitFileCount': 0,
        'dataItems': '',
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '计量单位',
        'fieldName': null,
        'formulaCondition': null,
        'formulaConditionText': null,
        'filterRuleText': null,
        'isRefByBusinessData': 0,
        'orderBy': 7,
        'parentName': null,
        'isOneLine': false,
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false,
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false,
        'fieldType': null,
        'groupType': 0,
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': false
      },
      {
        'id': '043da7d0-70c0-e811-80c3-00155d0a2546',
        'name': '文本',
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546',
        'isSystem': false,
        'isReadonly': true,
        'defaultValue': '默认文本 只读',
        'propertyType': 0,
        'serviceLine': '运营',
        'modifyReasonReq': false,
        'isMustFill': false,
        'valueType': '文本',
        'remark': '说明',
        'unit': '',
        'dec': 2,
        'limitFileCount': 0,
        'dataItems': '',
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '',
        'fieldName': null,
        'formulaCondition': null,
        'formulaConditionText': null,
        'filterRuleText': null,
        'isRefByBusinessData': 0,
        'orderBy': 1,
        'parentName': null,
        'isOneLine': false,
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false,
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false,
        'fieldType': null,
        'groupType': 0,
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': false
      },
      {
        'id': 'dc418f6d-72c0-e811-80c3-00155d0a2546',
        'name': '汇总计算',
        'groupId': 'f75c56c0-70c0-e811-80c3-00155d0a2546',
        'isSystem': false,
        'isReadonly': false,
        'defaultValue': '',
        'propertyType': 0,
        'serviceLine': '运营',
        'modifyReasonReq': false,
        'isMustFill': false,
        'valueType': '数值',
        'remark': '通过列表数据汇总计算',
        'unit': '',
        'dec': 2,
        'limitFileCount': 0,
        'dataItems': '',
        'businessObjectName': '',
        'legalPersonCompanyUrl': null,
        'businessParamName': '',
        'fieldName': null,
        'formulaCondition': '{"formulaSummary":"项目.列表表内编辑.分数"}',
        'formulaConditionText': '汇总计算=Sum([项目.列表表内编辑.分数])',
        'filterRuleText': '',
        'isRefByBusinessData': 0,
        'orderBy': 8,
        'parentName': null,
        'isOneLine': false,
        'displayFields': null,
        'displayFields__text': '',
        'IsHidden': false,
        'DBKey': null,
        'DisKey': null,
        'isPrimary': false,
        'fieldType': null,
        'groupType': 0,
        'dataFromType': 0,
        'canSetPrimary': 0,
        'canCancelPrimary': 0,
        'belongProductBusinessObjectGUID': null,
        'belongProductGroupId': null,
        'interfaceId': null,
        'isMulti': false
      }
    ],
    'groupType': 1,
    'dataFromType': 1,
    'refBusinessObjectGUID': null,
    'groupField': '',
    'groupField__text': '',
    'sumField': '',
    'sumField__text': '',
    'refBusinessObjectGroupName': '',
    'refBusinessObjectGroupId': null,
    'selectSumObjectValue': '',
    'selectSumObjectValue__text': '',
    'orderBy': 31,
    'regionId': 'd8f50b89-430d-45c1-af1e-c2658594b07a',
    'displayStyle': '有边框',
    'interfaceId': null,
    'interfaceField': '',
    'initializationData': null,
    'dataModelType': '在表编辑',
    'labelWidth': 0
  },
]
    }
  }

}
</script>
